### ISSUE TITLE
BasePage View Model Collisions

### ISSUE THREAD

**Issue by burkeholland** [ignaciofuentes/nativescript-template-drawer-ts#1]
This is great work! One of the things that I noticed is that there is no guidance on how to add a view model to the main content.

For instance, you may want to add a view model on the home page `loaded` event

```
let vm = new Observable({ someProps: 'someProps' });

class HomePage extends BasePage {
    loaded = (args) => {
        let page = args.object;
        page.bindingContext = vm;

        super(args);
    }
}
```

But there are two problems there
1. All of the functions on the base class are instance members, which means you cannot call `super`. 
2. Even if you changed them to functions (take away lambdas), the call to the super method would override the binding context for the whole page.

The way that I _think_ this should be done is to create a BasePage class that has an interface which requires you to implement the BasePage observable, which should then extend your observable with the drawer state. Still, this isn't the best solution since you're monkey patching someone else's object.

Any other ideas on how this could be done?

**Comment by ignaciofuentes** [comment]
I have created a branch with a proposal on how to get around this
https://github.com/ignaciofuentes/nativescript-template-drawer-ts/tree/abstract-basepage-class

The idea is that BasePage is an abstract class that exposes a mainContentLoaded function that should be implemented by other pages:

`abstract mainContentLoaded(args:EventData);`

With this in place the HomePage class now must implement this function:

```
let vm = new Observable({ myText: 'This is the home page' });
class HomePage extends BasePage{

    mainContentLoaded(args:EventData){
        let view = <View>args.object;
        view.bindingContext = vm;
    }
...
}
```

In order for this to work the relevant "main content" should simply set that as its loaded event.

```
    <drawer:rad-side-drawer.mainContent>

      <!-- Home page contents -->
      <stack-layout loaded="mainContentLoaded">
        <image src="https://i.imgur.com/LY3cb3A.png" id="logo" tap="fun" height="100" margin="20 0 0 0" />
        <label text="{{ myText }}" margin="20" horizontalAlignment="center" textWrap="true" />
      </stack-layout>

    </drawer:rad-side-drawer.mainContent>
```

I think this could allow for a nice architecture from which users can build up :)

Thoughts?

**Comment by tjvantoll** [comment]
I like this approach—a lot. I never even thought to use a separate `bindingContext` on the page’s primary component. I tried tried this out and it works great.

**Comment by tjvantoll** [comment]
I think my only thing to add is that this could use a few comments so people realize what `mainContentLoaded` is and why you must add it to each other page.
