### ISSUE TITLE
showOverNavigation

### ISSUE THREAD

**Issue by aronsuarez** [ignaciofuentes/nativescript-template-drawer-ts#2]
Hi this is a great work!

I have a small problem, when i set the showOverNavigation="true" then i can only switch one time, then i can't show the drawer on the second view.

Do you have a solution for this?

**Comment by shnhwk** [comment]
I'm running into this same issue. Come across a fix yet?

**Comment by ignaciofuentes** [comment]
I have added this on v 1.3.1
